version: "3.9"
services:
  user_app1:
    image: vulnerable_web
    container_name: user_app1
    networks:
      global_macvlan_net:
        ipv4_address: 192.168.100.1
    ports:
      - "8080:80"
    volumes:
      - ./user_app1/html:/var/www/html:z

networks:
  global_macvlan_net:
    external: true
  default:
