version: "3.9"
services:
  user_app1:
    image: vulnerable_web   # Replace with your vulnerable web image
    container_name: user_app1
    networks:
      user_app1_net:
        ipv4_address: 192.168.100.1
    ports:
      - "8080:80"  # Optional: for host testing if needed
    volumes:
      - ./user_app1/html:/var/www/html:z

networks:
  user_app1_net:
    external: true
  default: